server:
  port: 9000

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    
rabbitmq:
   addresses: localhost:5672
   queue: OrdersForDelivery
   exchange-name: exchangeDelivery
   routing-key: deliverOrder